s = set()

f1 = input('Enter the first number: ')
s.add(int(f1))
f2 = input('Enter the second number: ')
s.add(int(f2))
f3 = input('Enter the third number: ')
s.add(int(f3))
f4 = input('Enter the fourth number: ')
s.add(int(f4))
f5 = input('Enter the fifth number: ')
s.add(int(f5))
f6 = input('Enter the sixth number: ')
s.add(int(f6))
f7 = input('Enter the seventh number: ')
s.add(int(f7))
f8 = input('Enter the eigth number: ')
s.add(int(f8))

print(s)
print('This is your expected set of eight numbers.')